---

  # Initialize Swarm on Manager node and get the join-token.
  - name: Init Swarm Manager
    hosts: manager
    gather_facts: False
    remote_user: ubuntu
    become: true
    become_method: sudo
    tasks:
      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}
        ignore_errors: yes

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Manager Token
        command: docker swarm join-token manager -q
        register: manager_token

      - name: Show Manager Token
        debug: var=manager_token.stdout

      - name: Create Network
        command: docker network create --driver=overlay traefik-net
        ignore_errors: yes

  # Attach worker nodes using the join-token retrieved from manager node
  - name: Join Swarm Cluster
    hosts: workers
    remote_user: ubuntu
    gather_facts: False
    become: true
    become_method: sudo
    vars:
      token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ manager }}:2377
        register: worker
        ignore_errors: yes

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr

  # Run docker service commands to start traefik and whoami services on swarm cluster
  - name: Deploy Services
    hosts: manager
    remote_user: ubuntu
    gather_facts: False
    become: true
    become_method: sudo
    tasks:
      - name: Deploy Traefik Service
        command: docker service create \
                  --name traefik \
                  --constraint=node.role==manager \
                  --publish 80:80 --publish 90:8080 \
                  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
                  --network traefik-net \
                  traefik \
                  --docker \
                  --docker.swarmmode \
                  --docker.domain=traefik \
                  --docker.watch \
                  --logLevel=DEBUG \
                  --web

      - name: Deploy WhoAmI Service
        command: docker service create \
                  --replicas 3 \
                  --name whoami \
                  --label traefik.port=8080 \
                  --label traefik.docker.network=traefik-net \
                  --network traefik-net \
                  --publish 8080:8080 \
                  narramadan/springboot-whoami

  ################################################
  # Deploy docker services via docker-compose.yml
  ################################################
  # >>> When using docker-compose.yml, it is not working properly. Keeping this as backup <<<
  #
  #- name: Deploy Services
  #  hosts: manager
  #  gather_facts: False
  #  remote_user: ubuntu
  #  become: true
  #  become_method: sudo
  #  tasks:
  #    - copy:
  #        src: docker-compose.yml
  #        dest: /home/ubuntu/docker-compose.yml
  #
  #    - name: Invoke docker stack deploy
  #      command: docker stack deploy --compose-file /home/ubuntu/docker-compose.yml whoamistack